//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rental_WebCore2.Resources.Rental_Manager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Rental {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rental() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rental_WebCore2.Resources.Rental_Manager.Rental", typeof(Rental).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add photos.
        /// </summary>
        public static string Add_Photos {
            get {
                return ResourceManager.GetString("Add_Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Service.
        /// </summary>
        public static string Add_Service {
            get {
                return ResourceManager.GetString("Add_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add co-tenants.
        /// </summary>
        public static string Add_Tenants {
            get {
                return ResourceManager.GetString("Add_Tenants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add transport.
        /// </summary>
        public static string Add_Transport {
            get {
                return ResourceManager.GetString("Add_Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of money.
        /// </summary>
        public static string Amount_Money {
            get {
                return ResourceManager.GetString("Amount_Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset handover.
        /// </summary>
        public static string Asset_Handover {
            get {
                return ResourceManager.GetString("Asset_Handover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset name.
        /// </summary>
        public static string Asset_Name {
            get {
                return ResourceManager.GetString("Asset_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Type.
        /// </summary>
        public static string Asset_Type {
            get {
                return ResourceManager.GetString("Asset_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products with 1 -&gt; 5 days to pay..
        /// </summary>
        public static string Attention_1 {
            get {
                return ResourceManager.GetString("Attention_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products with 1-&gt; 5 days are due to pay and products not paid..
        /// </summary>
        public static string Attention_2 {
            get {
                return ResourceManager.GetString("Attention_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contracts are about to expire.
        /// </summary>
        public static string Attention_3 {
            get {
                return ResourceManager.GetString("Attention_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contracts need to be liquidated.
        /// </summary>
        public static string Attention_4 {
            get {
                return ResourceManager.GetString("Attention_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car color.
        /// </summary>
        public static string Car_Color {
            get {
                return ResourceManager.GetString("Car_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car name.
        /// </summary>
        public static string Car_Name {
            get {
                return ResourceManager.GetString("Car_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car service fee.
        /// </summary>
        public static string Car_Service_Fee {
            get {
                return ResourceManager.GetString("Car_Service_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car type.
        /// </summary>
        public static string Car_Type {
            get {
                return ResourceManager.GetString("Car_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        public static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract creation date.
        /// </summary>
        public static string Contract_Creation_Date {
            get {
                return ResourceManager.GetString("Contract_Creation_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contract is about to expire.
        /// </summary>
        public static string Contract_Exp {
            get {
                return ResourceManager.GetString("Contract_Exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract ID.
        /// </summary>
        public static string Contract_ID {
            get {
                return ResourceManager.GetString("Contract_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract information.
        /// </summary>
        public static string Contract_Infor_1 {
            get {
                return ResourceManager.GetString("Contract_Infor_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTRACT INFORMATION.
        /// </summary>
        public static string Contract_Infor_2 {
            get {
                return ResourceManager.GetString("Contract_Infor_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts need to liquidate.
        /// </summary>
        public static string Contract_Liquidate {
            get {
                return ResourceManager.GetString("Contract_Liquidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Contract_Liquidate_Button {
            get {
                return ResourceManager.GetString("Contract_Liquidate_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creat contract.
        /// </summary>
        public static string Creat_Contract_1 {
            get {
                return ResourceManager.GetString("Creat_Contract_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREAT CONTRACT.
        /// </summary>
        public static string Creat_Contract_2 {
            get {
                return ResourceManager.GetString("Creat_Contract_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creat invoice.
        /// </summary>
        public static string Creat_Invoice {
            get {
                return ResourceManager.GetString("Creat_Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID.
        /// </summary>
        public static string Customer_ID {
            get {
                return ResourceManager.GetString("Customer_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer information.
        /// </summary>
        public static string Customer_Infor {
            get {
                return ResourceManager.GetString("Customer_Infor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name.
        /// </summary>
        public static string Customer_Name {
            get {
                return ResourceManager.GetString("Customer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of delivery.
        /// </summary>
        public static string Date_Of_Delivery {
            get {
                return ResourceManager.GetString("Date_Of_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of payment.
        /// </summary>
        public static string Date_Of_Payment {
            get {
                return ResourceManager.GetString("Date_Of_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day/Month/Year.
        /// </summary>
        public static string Day_Month_Year {
            get {
                return ResourceManager.GetString("Day_Month_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete information.
        /// </summary>
        public static string Delete_Information {
            get {
                return ResourceManager.GetString("Delete_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string Deposit {
            get {
                return ResourceManager.GetString("Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail contract.
        /// </summary>
        public static string Detail_Contract {
            get {
                return ResourceManager.GetString("Detail_Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit information.
        /// </summary>
        public static string Edit_Informatin {
            get {
                return ResourceManager.GetString("Edit_Informatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective date.
        /// </summary>
        public static string Effective_Date {
            get {
                return ResourceManager.GetString("Effective_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity and water.
        /// </summary>
        public static string Electricity_Water {
            get {
                return ResourceManager.GetString("Electricity_Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELECTRICITY WATER MANAGEMENT.
        /// </summary>
        public static string Electricity_Water_Management {
            get {
                return ResourceManager.GetString("Electricity_Water_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty house.
        /// </summary>
        public static string Empty_House {
            get {
                return ResourceManager.GetString("Empty_House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty room.
        /// </summary>
        public static string Empty_Room {
            get {
                return ResourceManager.GetString("Empty_Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter unit price and quantity for service.
        /// </summary>
        public static string Enter_Unit_Prive_And_Quantity_Service {
            get {
                return ResourceManager.GetString("Enter_Unit_Prive_And_Quantity_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance.
        /// </summary>
        public static string Finance {
            get {
                return ResourceManager.GetString("Finance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date.
        /// </summary>
        public static string From_date {
            get {
                return ResourceManager.GetString("From_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hired.
        /// </summary>
        public static string Hired {
            get {
                return ResourceManager.GetString("Hired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hired house.
        /// </summary>
        public static string Hired_House {
            get {
                return ResourceManager.GetString("Hired_House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hired room.
        /// </summary>
        public static string Hired_Room {
            get {
                return ResourceManager.GetString("Hired_Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        public static string House {
            get {
                return ResourceManager.GetString("House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID_Number {
            get {
                return ResourceManager.GetString("ID_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity card.
        /// </summary>
        public static string Identity_Card {
            get {
                return ResourceManager.GetString("Identity_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index final.
        /// </summary>
        public static string Index_Final {
            get {
                return ResourceManager.GetString("Index_Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index head.
        /// </summary>
        public static string Index_Head {
            get {
                return ResourceManager.GetString("Index_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Into money.
        /// </summary>
        public static string Into_Money {
            get {
                return ResourceManager.GetString("Into_Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice History.
        /// </summary>
        public static string Invoice_History {
            get {
                return ResourceManager.GetString("Invoice_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice information.
        /// </summary>
        public static string Invoice_Infor {
            get {
                return ResourceManager.GetString("Invoice_Infor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVOICE MANAGEMENT.
        /// </summary>
        public static string Invoice_Management {
            get {
                return ResourceManager.GetString("Invoice_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latch date.
        /// </summary>
        public static string Latch_Date {
            get {
                return ResourceManager.GetString("Latch_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latch for month.
        /// </summary>
        public static string Latch_For_Month {
            get {
                return ResourceManager.GetString("Latch_For_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latch hour.
        /// </summary>
        public static string Latch_Hour {
            get {
                return ResourceManager.GetString("Latch_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latched.
        /// </summary>
        public static string Latched {
            get {
                return ResourceManager.GetString("Latched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License plate.
        /// </summary>
        public static string License_Plate {
            get {
                return ResourceManager.GetString("License_Plate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquidation date.
        /// </summary>
        public static string Liquidation_Date {
            get {
                return ResourceManager.GetString("Liquidation_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquidation of contracts.
        /// </summary>
        public static string Liquidation_Of_Contracts {
            get {
                return ResourceManager.GetString("Liquidation_Of_Contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of cost.
        /// </summary>
        public static string Name_Of_Cost {
            get {
                return ResourceManager.GetString("Name_Of_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name property.
        /// </summary>
        public static string Name_Property {
            get {
                return ResourceManager.GetString("Name_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet latch.
        /// </summary>
        public static string Not_Yet_Latch {
            get {
                return ResourceManager.GetString("Not_Yet_Latch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Overdue payment.
        /// </summary>
        public static string Overdue_Payment {
            get {
                return ResourceManager.GetString("Overdue_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payer.
        /// </summary>
        public static string Payer {
            get {
                return ResourceManager.GetString("Payer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment by.
        /// </summary>
        public static string Payment_By {
            get {
                return ResourceManager.GetString("Payment_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment month.
        /// </summary>
        public static string Payment_Month {
            get {
                return ResourceManager.GetString("Payment_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The person signing the contract.
        /// </summary>
        public static string Person_Signing_Contract {
            get {
                return ResourceManager.GetString("Person_Signing_Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone_Number {
            get {
                return ResourceManager.GetString("Phone_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print contract.
        /// </summary>
        public static string Print_Contract {
            get {
                return ResourceManager.GetString("Print_Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCT CONTRACT MANAGAMENT.
        /// </summary>
        public static string Product_Contract_Management {
            get {
                return ResourceManager.GetString("Product_Contract_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product overdue payment.
        /// </summary>
        public static string Product_Overdue_Payment {
            get {
                return ResourceManager.GetString("Product_Overdue_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products need to record electricity and water.
        /// </summary>
        public static string Product_Record_Elect_Water {
            get {
                return ResourceManager.GetString("Product_Record_Elect_Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products up to the month of payment.
        /// </summary>
        public static string Products_Month_Payment {
            get {
                return ResourceManager.GetString("Products_Month_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record electricity/water.
        /// </summary>
        public static string Record_Electricity_Water {
            get {
                return ResourceManager.GetString("Record_Electricity_Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register service.
        /// </summary>
        public static string Register_Service {
            get {
                return ResourceManager.GetString("Register_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental and service fees.
        /// </summary>
        public static string Rental_And_Service_Fees {
            get {
                return ResourceManager.GetString("Rental_And_Service_Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental fee.
        /// </summary>
        public static string Rental_Fee {
            get {
                return ResourceManager.GetString("Rental_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renter.
        /// </summary>
        public static string Renter {
            get {
                return ResourceManager.GetString("Renter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the project .
        /// </summary>
        public static string Select_Project {
            get {
                return ResourceManager.GetString("Select_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVICE MANAGEMENT.
        /// </summary>
        public static string Service_Management {
            get {
                return ResourceManager.GetString("Service_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting price service.
        /// </summary>
        public static string Setting_Price_Service {
            get {
                return ResourceManager.GetString("Setting_Price_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared tenants.
        /// </summary>
        public static string Shared_Tenants {
            get {
                return ResourceManager.GetString("Shared_Tenants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic.
        /// </summary>
        public static string Statistic {
            get {
                return ResourceManager.GetString("Statistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table service.
        /// </summary>
        public static string Table_Service {
            get {
                return ResourceManager.GetString("Table_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        public static string Tenant {
            get {
                return ResourceManager.GetString("Tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term payment.
        /// </summary>
        public static string Term_Payment {
            get {
                return ResourceManager.GetString("Term_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date.
        /// </summary>
        public static string To_Date {
            get {
                return ResourceManager.GetString("To_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total money.
        /// </summary>
        public static string Total_Money {
            get {
                return ResourceManager.GetString("Total_Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        public static string Transport {
            get {
                return ResourceManager.GetString("Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of fee.
        /// </summary>
        public static string Type_Of_Fee {
            get {
                return ResourceManager.GetString("Type_Of_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of service.
        /// </summary>
        public static string Type_Of_Service {
            get {
                return ResourceManager.GetString("Type_Of_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit price.
        /// </summary>
        public static string Unit_Price {
            get {
                return ResourceManager.GetString("Unit_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle owner.
        /// </summary>
        public static string Vehicle_Owner {
            get {
                return ResourceManager.GetString("Vehicle_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
